#!/usr/bin/env bash
# #############################################################################
# generate_inventory.sh — regenerate the repository inventory from the live org.
#
# Emits a candidate `locals { inventory = { ... } }` block to stdout (and to
# repos_data.generated.tf). It does NOT overwrite the curated repos_data.tf,
# because tiers/descriptions are human-maintained. Merge the diff by PR.
#
# Usage:  ORG=Via-Vitae ./scripts/generate_inventory.sh
# #############################################################################
set -euo pipefail

ORG="${ORG:-Via-Vitae}"
OUT="${OUT:-repos_data.generated.tf}"

command -v gh >/dev/null 2>&1 || { echo "gh CLI required" >&2; exit 1; }

# Infer a tier from the repo name (operator can override after review).
infer_tier() {
  case "$1" in
    .github) echo "meta" ;;
    viavitae-landing-*) echo "site" ;;
    viavitae-api|viavitae-clients|viavitae-web|viavitae-brand|viavitae-demos) echo "app" ;;
    viavitae-infra|viavitae-observability|viavitae-runbooks|viavitae-reusable-workflows|viavitae-template|viavitae-qa) echo "platform" ;;
    *) echo "control" ;;
  esac
}

{
  echo "# GENERATED by scripts/generate_inventory.sh on $(date -u +%FT%TZ)."
  echo "# Review and merge into repos_data.tf by PR. Do not commit this file as-is."
  echo "locals {"
  echo "  inventory_candidate = {"

  # name<TAB>visibility<TAB>description (base64-free, jq-escaped)
  gh api "orgs/${ORG}/repos?per_page=100&type=all" \
    --jq '.[] | [.name, .visibility, (.description // "")] | @tsv' |
  while IFS=$'\t' read -r name vis desc; do
    tier="$(infer_tier "$name")"
    # Escape double quotes in description for HCL.
    desc_esc="${desc//\"/\\\"}"
    echo "    \"${name}\" = {"
    echo "      description  = \"${desc_esc}\""
    echo "      visibility   = \"${vis}\""
    echo "      tier         = \"${tier}\""
    echo "      manage_files = false"
    echo "    }"
  done

  echo "  }"
  echo "}"
} | tee "${OUT}"

echo "" >&2
echo "Wrote candidate inventory to ${OUT}. Diff against repos_data.tf and merge by PR." >&2
